Quiz_Proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quizes import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sgin/', views.index),
    path('dash/', views.dash),
    path('', include('quizes.urls', namespace='quizes')),
    # path('sgin/', views.sgin),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path


from . import views
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,

)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),

]

questions/models.py
from django.db import models
from quizes.models import Quiz

# Create your models here.


class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizes/models.py
from django.db import models
import random

# Create your models here.


DIFF_CHOICES = (
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard'),
)


class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(
        help_text="required score in %")
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User

# Create your models here.


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result
from django.http import HttpResponse

# Create your views here.


class QuizListView(ListView):
    model = Quiz
    # ProQuiz, WebQuiz, DataQuiz
    template_name = 'quizes/main.html'


def index(request):
    return render(request, 'quizes/sgin.html')


def dash(request):
    return render(request, 'quizes/dash.html')


# def sgnin(request):
#     return render(request, 'quizes/sgnin.html')


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    # ProQuiz = ProQuiz.objects.get(pk=pk)
    # WebQuiz=WebQuiz.objects.get(pk=pk)
    # DataQuiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

    # Test


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    # print(request.POST)
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        print(data_)
        data_.pop('csrfmiddlewaretoken')
        print(data_)

        for k in data_.keys():
            print('keys: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)
            print("selected : ", a_selected)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append(
                    {str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

    return JsonResponse({'text': 'works'})

results/views.py
from django.shortcuts import render

# Create your views here.

quizes/templates/quizes/blank.html
{% extends 'base.html' %}


    
    {% block title %}
    Log In
    {% endblock title %}

  {% block content %}

    
 
    <form class="form-signin">
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
 
    {% endblock content %}

quizes/templates/quizes/dash.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div id="dashboard"> </div>

quizes/templates/quizes/main.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

<script src="{% static 'quizes/min.js' %}" defer></script>

{% endblock scripts %}



    {% block title %}
    Home
    {% endblock title %}

    {% block content %}

    <!-- Modal -->
    <div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body-confirm"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    <button type="button" id="start-button" class="btn btn-success">Yes</button>
                </div>
            </div>
        </div>
    </div>

 
    <!-- Jumbo tron1 Intro -->


    <div class="jumbotron jumbotron-fluid jumbointro" data-aos="fade-up" data-aos-offset="200" data-aos-delay="50"
        data-aos-duration="1000" id="About" style="background-color: white;">

        <!-- Bootstrap Grid system 1 -->

        <div class="container-fluid">
            <div class="row" id>

                <!-- Right Side -->

                <div class="col-xs-12 col-sm-12 col-md-12 col-xl-6 " class="cen">

                    <h1 class="display-4 " id="kk "><strong><span
                                class="badge rounded-pill bg-primary">YunavQ</span></strong></h1>
                    <br><br>
                    <p class="lead ">
                        If you Were looking for a Platform Where you Could Pracrice some Important Programing Concepts?
                    </p>
                    <p class="lead">Well then you are at the right place , At <span
                            class="badge rounded-pill bg-danger">YunavQ</span>
                        You get all of it with beautiful Interface to warm up your mind and be
                        hooked to application keep you hooked,</p>

                </div>


                <!-- Left side quiz list -->
                <div class="col-xs-12 col-sm-12 col-md-12 col-xl-6 thumbnail" class="cen">




                    <div class="accordion accordion-flush" id="accordionFlushExample">
                        <div class="accordion-item">
                            <div class="c">
                                <h2 class="accordion-header" id="flush-headingOne">
                                    <button class="accordion-button collapsed cenb1" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#flush-collapseOne"
                                        aria-expanded="false" aria-controls="flush-collapseOne">
                                        <span class="badge rounded-pill bg-success">Computer Science Quizzes</span>
                                    </button>
                                </h2>
                            </div>
                            <div id="flush-collapseOne" class="accordion-collapse collapse"
                                aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                                <div class="accordion-body">
                                    <ul>

                                        {% for obj in object_list %}

                                        <!--data-typee="{{obj.type}}"-->
                                        <button class="btn btn-link modal-button" data-pk="{{obj.pk}}"
                                            data-quiz="{{obj.name}}" data-questions="{{obj.number_of_questions}}"
                                            data-difficulty="{{obj.difficluty}}" data-time="{{obj.time}}"
                                            data-pass="{{obj.required_score_to_pass}}" data-toggle="modal"
                                            data-target="#quizStartModal">
                                            <span class="badge rounded-pill bg-dark"> {{obj.name}}</span>

                                        </button><br>

                                        {% endfor %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div>
                            <img class="imspace" src="{% static 'quizes/download.png' %}" alt="My image">
                        </div>

                        <center>
                            



                    </div>


                </div>
            </div>
            <!-- End of Grid1 -->


            <hr class="my-4 " />
            <br>


            {% endblock content %}

quizes/templates/quizes/quiz.html
 {% extends "base.html" %}


{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/q.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
    <span class="badge badge-pill badge-dark" ><h1><b>{{obj.name}}</b></h1></span>
    <br>
    <br>
    <span class="badge badge-pill badge-primary" > <p>score to pass: {{obj.required_score_to_pass}}%</p></span>

    </div>
   
    <div class="col text-right" id="timer-box"></div>
</div>
<br>
<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
<div id="dashboard"></div>

{% endblock content %}

quizes/templates/quizes/sgin.html
{% extends 'base.html' %}


    
    {% block title %}
    Log In
    {% endblock title %}

  {% block content %}

    
 
    <form class="form-signin">
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
 
    {% endblock content %}

templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    
    
    <!-- Bootstrap CSS -->
    
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- jquery -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!--Js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.umd.min.js"
        integrity="sha512-dG5ZzvFUfkBdjYdJbsKdGGh8tOa9fv9wHmiChCFJYHRIW1XgfxN2cGzt2HaEPeunXqbAQXBOJvSBQpGOl0qikw=="
        crossorigin="anonymous"></script>

    <!-- custom css & js-->
    
    <link rel="stylesheet" href={% static 'Bootstrap.css' %}>


    <!-- test styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href={% static 'Bootstrap.css' %}>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.umd.min.js"
        integrity="sha512-dG5ZzvFUfkBdjYdJbsKdGGh8tOa9fv9wHmiChCFJYHRIW1XgfxN2cGzt2HaEPeunXqbAQXBOJvSBQpGOl0qikw=="
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />


   

    {% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script> 
    {% endblock scripts %}

    <title>Yunav Quiz | {% block title %}{% endblock title %}</title>
  </head>
  <body>
  
  <!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-confirm"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                <button type="button" id="start-button" class="btn btn-success">Yes</button>
            </div>
        </div>
    </div>
</div>

    <!--                  Navbar                              -->




    <nav class="navbar navbar-expand-lg navbar-dark bg-dark " id="Home">
        <div class="container-fluid container-fluid-wh">
            <a class="navbar-brand" href="#">
                <nav class="navbar navbar-dark bg-dark">
                    <div class="container-fluid">
                        <a href="{% url 'quizes:main-view' %}" class="navbar-brand" href="#" style="margin-bottom: 10px; margin-left: 0px;">
                           <span class="badge rounded-pill bg-primary" id="HomeJs">Yunav Quiz</span>
                        </a>
                    </div>
                </nav>
            </a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse elemar " id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="{% url 'quizes:main-view' %}" class="nav-link active" aria-current="page" href="#Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="/blankmin/" class="nav-link" id="aboutd">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Quizes
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{% comment %} 
                            <li><a class="dropdown-item" href="#ToneDetector"></a>fvrf</li>
                            <li><a class="dropdown-item" href="#Products">Products</a></li> {% endcomment %}
                            <li>
                            <a class="dropdown-item" href="#Products">
                                    {% for obj in object_list %}
                                    
                                    <!--data-typee="{{obj.type}}"-->
                                    <button class="btn btn-link modal-button" data-pk="{{obj.pk}}"
                                        data-quiz="{{obj.name}}" data-questions="{{obj.number_of_questions}}"
                                        data-difficulty="{{obj.difficluty}}" data-time="{{obj.time}}"
                                        data-pass="{{obj.required_score_to_pass}}" data-toggle="modal"
                                        data-target="#quizStartModal">
                                        <span class="badge rounded-pill bg-info" > {{obj.name}}</span>

                                    </button><br>

                                    {% endfor %}
                            </a>
                                </li>
                            <!-- <li>
                                <hr class="dropdown-divider">
                            </li> -->
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Footerr" tabindex="-1" aria-disabled="False">Contact</a>
                    </li>
                </ul>
                {% comment %} <form class="d-flex">

                    <button class="btn btn-outline-success btn-success searchborder" type="submit"><a href="#"
                            style="text-decoration: none; color: white">Register</a></button>
                </form> {% endcomment %}
            </div>
        </div>
    </nav>
    <!-- End of Navbar -->

    <br>


    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!--- Connect Links-->
    <div class="container-fluid padding">
        <div class="row text-center padding">
            <div class="col-12">
                <h2 id="Connect">Connect</h2>
            </div>
            <div class="col-12 social padding">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#/"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </div>
    <!-- End Connection Links -->

    <!--Footer-->

    <br><br><br><br><br><br><br><br><br><br>
    <footer style="background-color:#262626; color:white" id="Footerr">
        <div class="container-fluid padding" data-aos="fade-up" data-aos-offset="200" data-aos-delay="50"
            data-aos-duration="1000">
            <div class="row text-center">

                <div class="col-md-4 pt-0">
                    <hr class="light">
                    <div class="footer-image" style="margin-top: 16px; margin-bottom: 16.5px;">
                        <span class="badge rounded-pill bg-primary">YunavQ</span>
                    </div>
                    <hr class="light" />
                    <p>9997-562-020</p>
                    <p>aakashsrivastava62@gmail.com</p>
                    <p>yunavyachi@gmail.com</p>
                    <p>New Delhi, India</p>
                </div>
                <div class="col-md-4">
                    <hr class="light" />
                    <h5>Our hours</h5>
                    <hr class="light" />
                    <p>Monday - Friday: 10am - 8pm</p>
                    <p>Saturday & Sunday: Closed</p>
                </div>
                <div class="col-md-4">
                    <hr class="light" />
                    <h5>Service Area</h5>
                    <hr class="light" />
                    <p>Delhi, New Delhi</p>
                    <p>Noida, Uttar Pradesh</p>
                    <p>Gurugram, Haryana</p>
                    <p>Bangaluru, Karnataka</p>
                </div>
                <div class="col-12">
                    <hr class="light-100" />
                    <h5>&copy; YunavQ Est. 2021</h5>
                </div>
            </div>
        </div>
    </footer>

    <!--End Footer-->

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) 4.6 -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js "
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns "
        crossorigin="anonymous "></script>
    <!-- Option 2: Separate Popper and Bootstrap JS 5.0 -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js "
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p "
        crossorigin="anonymous "></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js "
        integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ "
        crossorigin="anonymous "></script>

    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
   
   
    <script>
        AOS.init();
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


  </body>
  </body>
</html>